Update trufflehog.yml

diff --git a/.github/workflows/trufflehog.yml b/.github/workflows/trufflehog.yml
--- a/.github/workflows/trufflehog.yml
+++ b/.github/workflows/trufflehog.yml
@@ -1,43 +1,90 @@
-name: Secret Scanning
+name: Detect Secrets
 
 on:
   push:
     branches:
-      - main
+      - master
   pull_request:
     branches:
-      - main
+      - master
 
 jobs:
-  secret_scanning:
-    name: Secret Scanning
+  ubuntu:
     runs-on: ubuntu-latest
-
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Set up Python
+      - name: Set Python 3 as default
         uses: actions/setup-python@v2
         with:
-          python-version: 3.9
+          python-version: 3
 
-      - name: TruffleHog OSS
-        uses: trufflesecurity/trufflehog@v3.41.1
-
-
-      - name: Run TruffleHog scan
-        if: ${{ always() }}
+      - name: Install detect-secrets using pip
         run: |
-          mkdir -p findings
-          sh -c 'trufflehog --regex --entropy=False . > findings/trufflehog_report.txt'
-        continue-on-error: true
-        env:
-          ARTIFACTS_DIR: ${{ github.workspace }}/findings
+          python -m pip install detect-secrets
 
-      - name: Upload findings as artifacts
-        if: ${{ always() }}
+      - name: Run detect-secrets tool
+        run: |
+          detect-secrets --version
+          detect-secrets scan --all-files --force-use-all-plugins --exclude-files FETCH_HEAD > ${{ github.workspace }}/detect-secrets.json
+
+      - name: Publish results in the Pipeline Artifact
         uses: actions/upload-artifact@v2
         with:
-          name: TruffleHog Findings
-          path: ${{ env.ARTIFACTS_DIR }}
+          name: detect-secrets-ubuntu
+          path: ${{ github.workspace }}/detect-secrets.json
+
+      - name: Analyzing detect-secrets results
+        run: |
+          dsjson=$(cat ${{ github.workspace }}/detect-secrets.json)
+          echo "${dsjson}"
+
+          count=$(echo "${dsjson}" | jq -c -r '.results | length')
+
+          if [ $count -gt 0 ]; then
+            msg="Secrets were detected in code. ${count} file(s) affected."
+            echo "##[error]${msg}"
+            echo "##[task]${msg}."
+            exit 1
+          else
+            echo "No secrets detected."
+          fi
+
+  windows:
+    runs-on: windows-latest
+    steps:
+      - name: Set Python 3 as default
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3
+
+      - name: Install detect-secrets using pip
+        run: |
+          python -m pip install detect-secrets==1.0.3
+
+      - name: Run detect-secrets tool
+        run: |
+          detect-secrets --version
+          detect-secrets scan --all-files --force-use-all-plugins > ${{ github.workspace }}/detect-secrets.json
+
+      - name: Publish results in the Pipeline Artifact
+        uses: actions/upload-artifact@v2
+        with:
+          name: detect-secrets-windows
+          path: ${{ github.workspace }}/detect-secrets.json
+
+      - name: Analyzing detect-secrets results
+        run: |
+          $dsjson = Get-Content ${{ github.workspace }}/detect-secrets.json
+          Write-Output $dsjson
+
+          $dsObj = $dsjson | ConvertFrom-Json
+          $count = ($dsObj.results | Get-Member -MemberType NoteProperty).Count
+
+          if ($count -gt 0) {
+            $msg = "Secrets were detected in code. $count file(s) affected."
+            Write-Error $msg
+            Write-Host "##[error]$msg"
+            exit 1
+          }
+          else {
+            Write-Host "No secrets detected."
+          }
